### PR TITLE
fix: add secret

### PR DESCRIPTION
**Pull request by namjo**
Hello hairmare,

thanks for that hint. So hereby I am requesting you to merge my changes into your master branch.

**Another question**: I added a `supersecuresecret` into your _config.yml. In a real project, would one upload sensitive data like a secret to github? Would one do this only for "dev-reasons" and keep a different secret on the production server, far away from github's reach?

### CODE REVIEW

**Comment by hairmare** [comment]
There are some cases where making a difference between a "dev" and "production" secret might make sense. In most cases you would try not to add a secret to a public repo. Some folks I know use a separate private repo to contain just the secrets.

Most continuous integrations services also support some way of making an encrypted secret available for a build (ie. travis-ci has [encryption keys](https://docs.travis-ci.com/user/encryption-keys/)).

In this case the secret is a reCaptcha secret. Some might consider it easily available enough to not consider it abuseable. I'm not sure what kind of policy reCaptcha has for this.

**Comment by namjo** [comment]
Seems to be a complicated topic, but it feels like it makes sense. Wasn't ever aware of travis cli and .travis.yml to have ci on my github repo (even though I came across Travis before).
One last question (It s actually not such an important question ... I hope I didn t ask too much the last cpl of hours ... this is really my last ...): How can one enable autocompletion in travis cli? I was asked to install that feature ... at first time when I invoked travis, but typed in no ... now travis doesn t ask me again ... 
googled sth like "travis cli enable auto-completion", but no suitable answers ...

**Comment by hairmare** [comment]
I haven't used the travis cli in ages (I usually just hack the yaml manually).

It look like the travis cli does support auto-completion. When I call it, it asks to instrall it:

```
$ travis --help
Shell completion not installed. Would you like to install it now? |y| 
```

After answering with `y` and opening a new terminal autocompletion works on my bash:

```
$ travis en^T^T
enable        encrypt       encrypt-file  endpoint      env           
```

**Comment by namjo** [comment]
Yeah this is exactly the one I answered with n ... 
but anyway, it s not that important than having accomplished my first open source PR

**Pull request merged**
